server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # для React Router - все несуществующие пути отдаём на index.html,
    # чтобы прямые ссылки на /categories/1 и т.д. работали корректно
    location / {
        try_files $uri $uri/ /index.html;
    }
}
